columns_to_exclude = ['HIV_label',
'Hepatitis B_label', 
'Malaria_label', 
'Hepatitis C_label',
'Syphilis_label', 
'COVID_label', 
'Yellow Fever_label', 
'Lassa_label', 
'Ebola_label', 
'Marburg_label', 
'West Nile_label', 
'Zika_label', 
'CCHF_label', 
'Rift Valley_label', 
'Dengue_label', 
'ONN_label', 
'Mpox_label', 
'Chikungunya_label', 
'Hantavirus_label', 
'Measles_label', 
'Nipah_label', 
'Rabies_label', 
'HCOV HKU1_label', 
'HCOV NL63_label', 
'HCOV OC43_label', 
'FLU AV_label', 
'FLU BV_label', 
'HMPV_label', 
'HRSV_label', 
'HPIV 3_label', 
'Human herpesvirus_label', 
'Torque teno virus_label', 
'GB virus C_label', 
'Human mastadenovirus A_label', 
'assembly_from_seq', 
'date_crf',
'record_id',
'all-viral_label',
'all-viral-malaria_label',
'suspected_case1',
'suspected_case2',
'unitc_crf',
'previouslabs',
'previoustest_1',
'treated_history',
'suspected_case3',
'visit_history',
'previoustest_2',
'previoustest_3',
'previoustest_4',
'time3',
'hc_ppec',
'sharp_objectsc',
'housingother',
'roofingother',
'time4',
'family_fluidsc',
'comorbidityc'
]
